name: "Main / Pull requests build"

env:
  acapi_token: ${{secrets.ACAPI_TOKEN}}
# ArmorCode env
  armorcodehost: https://eu.armorcode.com
  product: webgoat
  subProduct: webgoat
  environment: Staging
  token: ${{secrets.ARMORCODE_TOKEN}}
  buildTool: GITHUB_ACTIONS
  buildNumber: ${{github.run_number}}
  end: 30
  
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest ]
        steps:
             # ArmorCode build gate
            - run: |
                  wget https://eu.armorcode.com/static/scripts/slastatus.sh
                  sh slastatus.sh
